[package]
name = "wacky_db"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
rusqlite = { version = "0.32.1", features = ["bundled"] }
rand = "0.8.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sqlparser = "0.51.0"
